# 네임스페이스 정의
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
# Jaeger 구성
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: monitoring
  labels:
    app: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:1.42
          ports:
            - containerPort: 6831
              protocol: UDP
            - containerPort: 6832
              protocol: UDP
            - containerPort: 5778
            - containerPort: 16686
            - containerPort: 4317
            - containerPort: 4318
            - containerPort: 14250
            - containerPort: 14268
            - containerPort: 14269
            - containerPort: 9411
          env:
            - name: COLLECTOR_ZIPKIN_HOST_PORT
              value: ":9411"
            - name: COLLECTOR_OTLP_ENABLED
              value: "true"
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          livenessProbe:
            httpGet:
              path: /
              port: 14269
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 14269
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: monitoring
  labels:
    app: jaeger
spec:
  type: NodePort
  ports:
    - port: 6831
      protocol: UDP
      targetPort: 6831
      name: udp-6831
    - port: 6832
      protocol: UDP
      targetPort: 6832
      name: udp-6832
    - port: 5778
      targetPort: 5778
      name: http-5778
    - port: 16686
      targetPort: 16686
      nodePort: 30686
      name: http-16686
    - port: 4317
      targetPort: 4317
      name: http-4317
    - port: 4318
      targetPort: 4318
      name: http-4318
    - port: 14250
      targetPort: 14250
      name: http-14250
    - port: 14268
      targetPort: 14268
      name: http-14268
    - port: 14269
      targetPort: 14269
      name: http-14269
    - port: 9411
      targetPort: 9411
      name: http-9411
  selector:
    app: jaeger